version: '2.4'
services:
  influxdb:
    image: hypriot/rpi-influxdb
    restart: always
    container_name: influxdb
    user: root
    ports:
      - 2003:2003
      - 8086:8086
      - 8089:8089/udp
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_HTTP_FLUX_ENABLED: 'true'
      #INFLUXDB_HTTP_AUTH_ENABLED: 'true'
      INFLUXDB_UDP_ENABLED: 'true'
      INFLUXDB_UDP_DATABASE: 'telegraf'
      INFLUXDB_ADMIN_USER: 'admin'
      INFLUXDB_ADMIN_PASSWORD: 'YOUR_ADMIN_PASSWORD'
      INFLUXDB_DB: 'telegraf'
      INFLUXDB_USER: 'telegraf'
      INFLUXDB_USER_PASSWORD: 'YOUR_USER_PASSWORD'
    
  chronograf:
    image: chronograf:latest
    restart: always
    container_name: chronograf
    ports:
      - 8888:8888
    volumes:
      - ./chronograf:/var/lib/chronograf
      
  grafana:
    image: grafana/grafana
    restart: always
    container_name: grafana
    user: root
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    # environment:
    #   GF_INSTALL_PLUGINS: 'grafana-clock-panel 1.0.1,grafana-simple-json-datasource 1.3.5'

  